def ad_script_19():
  modbus_add_signal("172.16.17.8", 255, 0, 1, "MODBUS_1")
  modbus_set_signal_update_frequency("MODBUS_1", 10)
  modbus_add_signal("172.16.17.8", 255, 1, 1, "MODBUS_2")
  modbus_set_signal_update_frequency("MODBUS_2", 10)
  modbus_add_signal("172.16.17.8", 255, 16, 0, "MODBUS_3")
  modbus_set_signal_update_frequency("MODBUS_3", 10)
  modbus_add_signal("172.16.17.8", 255, 17, 0, "MODBUS_4")
  modbus_set_signal_update_frequency("MODBUS_4", 10)
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 1)
  set_analog_outputdomain(1, 1)
  set_tool_voltage(24)
  set_standard_digital_input_action(0, "default")
  set_standard_digital_input_action(1, "default")
  set_standard_digital_input_action(2, "default")
  set_standard_digital_input_action(3, "default")
  set_standard_digital_input_action(4, "default")
  set_standard_digital_input_action(5, "default")
  set_standard_digital_input_action(6, "default")
  set_standard_digital_input_action(7, "default")
  set_tool_digital_input_action(0, "default")
  set_tool_digital_input_action(1, "default")
  modbus_set_runstate_dependent_choice("MODBUS_1",0)
  modbus_set_runstate_dependent_choice("MODBUS_2",0)
  set_tcp(p[0.0,0.0,0.125,0.0,0.0,0.0])
  set_payload(0.0)
  set_gravity([0.0, 0.0, 9.82])
  global force1=124.23835
  global count=1
  global i_var_1=1
  global select_no=1
  global u26426u24231=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global u24037u20855=get_forward_kin()
  $ 1 "BeforeStart"
  def add(a,b):
  return a+b
  end
  while (True):
    $ 3 "机器人程序"
    $ 4 "var_1≔'please input a:'"
    global var_1=request_integer_from_primary_client("please input a:")
    $ 5 "var_2≔'please input b:'"
    global var_2=request_integer_from_primary_client("please input b:")
    $ 6 "results≔add(var_1,var_2)"
    global results=add(var_1,var_2)
    $ 7 "等待: 5.0"
    sleep(5.0)
  end
end
